game/urls.py
from django.conf.urls import url

from game.views import CreateRaceView, RaceListView, JoinRaceView, WatchRaceView, LeaveRaceView, RefillView, \
    AjaxRaceStateView, SelectSkinView

app_name = 'game'

urlpatterns = [
    url(r'^create/', CreateRaceView.as_view(), name='create'),
    url(r'^$', RaceListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/join/$', JoinRaceView.as_view(), name='join'),
    url(r'^(?P<pk>\d+)/leave/$', LeaveRaceView.as_view(), name='leave'),
    url(r'^(?P<pk>\d+)/refill/$', RefillView.as_view(), name='refill'),
    url(r'^(?P<pk>\d+)/state/$', AjaxRaceStateView.as_view(), name='ajax_state'),
    url(r'^(?P<pk>\d+)/skin/$', SelectSkinView.as_view(), name='skin'),
    url(r'^(?P<pk>\d+)/$', WatchRaceView.as_view(), name='watch'),
]

tokenfight/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'^game/', include('game.urls', namespace='game')),

    url(r'^', include('front.urls', namespace='front')),
]

admin.site.site_title = 'CryptoRace.io admin'
admin.site.site_header = 'CryptoRace.io administration'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
import uuid

from decimal import Decimal, getcontext
from django.contrib.postgres.fields import JSONField
from django.core import validators
from django.db import models, transaction
from django.utils import timezone
from django.utils.functional import cached_property

from customer.models import Customer, Currency

START_PORTFOLIO_SUM = 100000


class Track(models.Model):
    name = models.CharField(max_length=255)
    length = models.DurationField(help_text='Format: "1 12:00:00" for 1 day and 12 hours')
    refills = models.IntegerField()
    cover = models.ImageField()

    def __str__(self):
        return '{self.name} ({self.length} days, {self.refills} refills)'.format(self=self)


class Race(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    track = models.ForeignKey(Track, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=24, decimal_places=18)
    racers_needed = models.IntegerField(validators=(validators.MinValueValidator(2), validators.MaxValueValidator(4)))
    create_datetime = models.DateTimeField(auto_now_add=True)
    started = models.BooleanField(default=False)
    start_datetime = models.DateTimeField(null=True, blank=True)
    finished = models.BooleanField(default=False)
    finish_datetime = models.DateTimeField(null=True, blank=True)
    _rankings = JSONField(null=True, blank=True)

    @transaction.atomic
    def start(self):
        # getcontext().prec = 18

        self.started = True
        self.start_datetime = timezone.now()
        self.save()
        for racer in self.racers.all():
            racer.fill_bids_with_percentages(START_PORTFOLIO_SUM)

    @transaction.atomic
    def finish(self):
        rankings_sum = {}
        rankings = []
        winner_racers = []
        for racer in self.racers.all():
            rankings_sum.setdefault(racer.portfolio_sum, []).append(racer)
        for i, key in enumerate(sorted(rankings_sum.keys(), reverse=True)):
            if i == 0:
                winner_racers = rankings_sum[key]
            rankings.append((rankings_sum[key][0].portfolio_diff_str, [racer.pk for racer in rankings_sum[key]]))

        # spread winnings to top racers
        winning = self.price * self.racers_count / len(winner_racers)
        for racer in winner_racers:
            racer.customer.balance += winning
            racer.customer.save()

        self.finished = True
        self.finish_datetime = timezone.now()
        self._rankings = rankings
        self.save()

    @cached_property
    def rankings(self):
        result = []
        for rank, row in enumerate(self._rankings, 1):
            result.append((rank, row[0], [Racer.objects.get(pk=pk) for pk in row[1]]))
        return result

    @cached_property
    def racers_count(self):
        return self.racers.count()

    @cached_property
    def is_ready(self):
        return self.racers_count >= self.racers_needed

    def get_racer_by_customer(self, customer):
        try:
            return self.racers.get(customer=customer)
        except (Racer.DoesNotExist, Racer.MultipleObjectsReturned):
            return None

    def __str__(self):
        return '#{} ({})'.format(self.pk, self.track)


class Racer(models.Model):
    race = models.ForeignKey(Race, on_delete=models.PROTECT, related_name='racers')
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, related_name='racers')
    bids = JSONField(default={}, editable=False)
    percentages = JSONField(editable=False)
    refills_used = models.IntegerField(default=0)

    def fill_bids_with_percentages(self, total, percentages=None):
        if percentages is None:
            percentages = self.percentages
        else:
            self.percentages = percentages
        bids = {}
        for (code, percent) in dict(percentages).items():
            try:
                currency_price = Currency.objects.get(code=code).price
                bids[code] = str(total * Decimal(percent) / currency_price)
            except Currency.DoesNotExist:
                continue
        self.bids = bids
        self.save()

    @cached_property
    def portfolio_sum(self):
        # getcontext().prec = 18

        result = Decimal(0)
        for code, bid in dict(self.bids).items():
            try:
                currency_price = Currency.objects.get(code=code).price
                result += Decimal(bid) * currency_price
            except Currency.DoesNotExist:
                continue
        return result

    @cached_property
    def portfolio_diff(self):
        return (self.portfolio_sum - START_PORTFOLIO_SUM) / START_PORTFOLIO_SUM

    @cached_property
    def portfolio_diff_str(self):
        return '{:+.2f}'.format(self.portfolio_diff * 100)

    @cached_property
    def bids_list(self):
        # getcontext().prec = 18

        result = []
        for code in self.percentages:
            try:
                currency = Currency.objects.get(code=code)
                bid = Decimal(dict(self.bids).get(code))
                result.append({
                    'currency': currency,
                    'percentage': bid * currency.price / self.portfolio_sum * 100,  # self.portfolio_sum is cached
                    'bid': bid
                })
            except Currency.DoesNotExist:
                continue
        return result

    @cached_property
    def has_refills_left(self):
        return self.refills_used < self.race.track.refills

    def __str__(self):
        return '{} (race {})'.format(self.customer, self.race)

game/views.py
from decimal import Decimal, getcontext

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import FormMixin, DeleteView, FormView, UpdateView

from customer.forms import CarSkinForm
from customer.models import Currency, Customer, CarSkin
from .forms import JoinRaceForm
from .models import Race, Track, Racer


class CreateRaceView(LoginRequiredMixin, CreateView):
    model = Race
    template_name = 'game/create_race.html'
    fields = ('track', 'racers_needed', 'price',)

    def get_success_url(self):
        return reverse('game:skin', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        ctx = super(CreateRaceView, self).get_context_data(**kwargs)
        ctx['tracks'] = Track.objects.all()
        return ctx

    def form_valid(self, form):
        result = super(CreateRaceView, self).form_valid(form)
        if settings.DEMO and self.request.GET.get('demo') is not None:
            percentages = {c.code: (1 if i == 0 else 0) for i, c in enumerate(Currency.objects.order_by('?'))}
            Racer.objects.create(race=self.object,
                                 customer=Customer.objects.exclude(user_id=self.request.user)
                                                          .filter(balance__gte=self.object.price).order_by('?').first(),
                                 percentages=percentages)
        return result


class RaceListView(ListView):
    model = Race
    template_name = 'game/race_list.html'
    queryset = Race.objects.all()
    paginate_by = 12

    def get_context_data(self, *args, **kwargs):
        ctx = super(RaceListView, self).get_context_data(*args, **kwargs)
        ctx['not_started'] = Race.objects.filter(started=False, finished=False)
        ctx['ongoing'] = Race.objects.filter(started=True, finished=False)
        if self.request.user.is_authenticated:
            ctx['joined_races'] = self.request.user.customer.racers.values_list('race__pk', flat=True)
        else:
            ctx['joined_races'] = []
        return ctx


class JoinRaceView(FormMixin, DetailView):
    model = Race
    template_name = 'game/join_race.html'
    queryset = Race.objects.all()
    form_class = JoinRaceForm

    def dispatch(self, request, *args, **kwargs):
        race = self.get_object()
        error = False

        if request.user.is_authenticated:
            if race.get_racer_by_customer(request.user.customer):
                messages.warning(request, 'You are already participating in this race')
                error = True
            elif race.finished:
                messages.warning(request, 'You cannot join this race anymore because it has already finished')
                error = True
            elif race.started:
                messages.warning(request, 'You cannot join this race anymore because it has already started')
                error = True
            elif request.user.customer.balance < race.price:
                messages.warning(request, 'Balance is not enough')
                error = True

            if not error:
                return super(JoinRaceView, self).dispatch(request, *args, **kwargs)
        else:
            messages.warning(request, 'You are not logged in')

        return redirect('game:watch', pk=race.pk)

    def get_success_url(self):
        return reverse('game:watch', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        ctx = super(JoinRaceView, self).get_context_data(**kwargs)
        ctx['currencies'] = Currency.objects.all()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # getcontext().prec = 18

        with transaction.atomic():
            Racer.objects.create(race=self.object,
                                 customer=self.request.user.customer,
                                 percentages=form.cleaned_data['percentages'])

            # subtract participation fee
            self.request.user.customer.balance -= self.object.price
            self.request.user.customer.save()

            if self.object.is_ready:
                self.object.start()

        messages.success(self.request, 'You have joined this race')

        return super(JoinRaceView, self).form_valid(form)


class RefillView(FormMixin, DetailView):
    model = Race
    template_name = 'game/join_race.html'
    queryset = Race.objects.all()
    form_class = JoinRaceForm

    def dispatch(self, request, *args, **kwargs):
        race = self.get_object()
        error = False

        if request.user.is_authenticated:
            racer = race.get_racer_by_customer(request.user.customer)
            if not racer:
                messages.warning(request, 'You are not participating in this race')
                error = True
            elif race.finished:
                messages.warning(request, 'You cannot refill in this race anymore because it has already finished')
                error = True
            elif not race.started:
                messages.warning(request, 'You cannot refill in this race because it has not yet started')
                error = True
            elif racer.refills_used >= race.track.refills:
                messages.warning(request, 'You have no more refills left')
                error = True

            if not error:
                return super(RefillView, self).dispatch(request, *args, **kwargs)
        else:
            messages.warning(request, 'You are not logged in')

        return redirect('game:watch', pk=race.pk)

    def get_success_url(self):
        return reverse('game:watch', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        ctx = super(RefillView, self).get_context_data(**kwargs)
        ctx['currencies'] = Currency.objects.all()
        return ctx

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # getcontext().prec = 18

        with transaction.atomic():
            racer = self.object.get_racer_by_customer(self.request.user.customer)
            racer.refills_used += 1  # racer gets saved in the next line call
            racer.fill_bids_with_percentages(racer.portfolio_sum, form.cleaned_data['percentages'])

        messages.success(self.request, 'You have refilled your car')

        return super(RefillView, self).form_valid(form)


class LeaveRaceView(DetailView):
    model = Race
    queryset = Race.objects.all()
    template_name = 'game/leave_race.html'

    def dispatch(self, request, *args, **kwargs):
        race = self.get_object()
        error = False

        if self.request.user.is_authenticated:
            if not race.get_racer_by_customer(request.user.customer):
                messages.warning(request, 'You are not participating in this race')
                error = True
            elif race.finished:
                messages.warning(request, 'You cannot leave this race anymore because it has already finished')
                error = True
            elif race.started:
                messages.warning(request, 'You cannot leave this race anymore because it has already started')
                error = True

            if not error:
                return super(LeaveRaceView, self).dispatch(request, *args, **kwargs)
        else:
            messages.warning(request, 'You are not logged in')

        return redirect('game:watch', pk=race.pk)

    def post(self, request, *args, **kwargs):
        # getcontext().prec = 18

        race = self.get_object()
        with transaction.atomic():
            request.user.customer.balance += race.price
            request.user.customer.save()
            race.get_racer_by_customer(request.user.customer).delete()

        messages.success(request, 'You have left this race')
        return redirect('game:watch', pk=race.pk)


class WatchRaceView(DetailView):
    model = Race
    template_name = 'game/watch_race.html'
    queryset = Race.objects.all()
    context_object_name = 'race'

    def get_context_data(self, **kwargs):
        ctx = super(WatchRaceView, self).get_context_data(**kwargs)
        ctx['currencies'] = Currency.objects.all()
        ctx['skins'] = CarSkin.objects.all()
        ctx['racers'] = sorted(self.object.racers.all(), key=lambda racer: racer.portfolio_sum, reverse=True)

        if self.request.user.is_authenticated:
            ctx['current_racer'] = self.object.get_racer_by_customer(self.request.user.customer)
        else:
            ctx['current_racer'] = None

        return ctx


class AjaxRaceStateView(DetailView):
    model = Race
    queryset = Race.objects.all()

    def get(self, request, *args, **kwargs):
        race = self.get_object()
        racers_data = []
        extra = {}
        if race.started and race.finished:
            for rank, diff, racers in race.rankings:
                for racer in racers:
                    racers_data.append({
                        'rank': rank,
                        'rank_suffix': {1: 'st.', 2: 'nd.', 3: 'rd.'}.get(rank, 'th.'),
                        'diff': diff,
                        'racer': {
                            'id': racer.id,
                            'username': racer.customer.username,
                            'avatar': racer.customer.avatar.url,

game/templates/game/create_race.html
{% extends 'base.html' %}
{% load staticfiles bootstrap4 %}

{% block head %}
  <title>Create race</title>
  <link rel="stylesheet" href="{% static 'css/for-form.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <div class="container d-flex justify-content-center">
      <h1 class="title-yellow">Create Race</h1>
    </div>
    <form method="post" class="form {% if form.errors %}errors{% endif %}">
      {% csrf_token %}
        {% bootstrap_form_errors form %}
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}
       <div class="form-group row">
         <label for="id_track" class="col-sm-1 offset-sm-2 col-form-label">Track:</label>
         <div class="col-sm-7">
             <select name="track" required id="id_track">
                 <option value="" selected>---------</option>
                 {% for track in form.fields.track.choices.queryset %}
                 <option value="{{ track.pk }}">{{ track.name }}</option>
                 {% endfor %}
             </select>
         </div>
       </div>
       <fieldset class="form-group">
         <div class="row">
           <legend class="col-form-label col-sm-1 offset-sm-2 pt-0">Racers:</legend>
           <div class="col-sm-7 d-flex">
             <div class="form-check">
               <input class="form-check-input" type="radio" name="racers_needed" id="gridRadios1" value="2" checked>
               <label class="form-check-label" for="gridRadios1">
                 <div class="chec-custom"></div>
                 2 racers
               </label>
             </div>
             <div class="form-check">
               <input class="form-check-input" type="radio" name="racers_needed" id="gridRadios2" value="3">
               <label class="form-check-label" for="gridRadios2">
                 <div class="chec-custom"></div>
                 3 racers
               </label>
             </div>
             <div class="form-check ">
               <input class="form-check-input" type="radio" name="racers_needed" id="gridRadios3" value="4" >
               <label class="form-check-label" for="gridRadios3">
                 <div class="chec-custom"></div>
                 4 racers
               </label>
             </div>
           </div>
         </div>
       </fieldset>
       <div class="form-group row">
          <label for="inputEmail3" class="col-sm-1 offset-sm-2 col-form-label">Price:</label>
          <div class="col-sm-7">
            <div class="input-group mb-2">
             <div class="input-group-prepend">
               <div class="input-group-text">ETH</div>
             </div>
             <input required type="text" name='price' class="form-control" id="inlineFormInputGroup" placeholder="1.5">
           </div>
          </div>
        </div>
        <div class="form-group row">
         <div class="col-sm-12 center-flex">
           <button type="submit" class="btn btn-lg btn-yellow">Create</button>
         </div>
        </div>
    </form>
  </div>
{% endblock %}

game/templates/game/join_race.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block head %}
  <title>Fuel</title>
  <link rel="stylesheet" href="/static/libs/ion.rangeSlider.css">
  <link rel="stylesheet" href="/static/css/fiel.css">
{% endblock %}
{% block script %}
  <script src='/static/js/picker.js'></script>
  <script src='/static/js/ion.rangeSlider.js'></script>
{% endblock %}

{% block content %}
<div class="container">
  <!-- <h2>Race #{{ object.pk }}</h2> -->
  <div class="container d-flex justify-content-center">
    <h1 class="title-yellow">FILL THE CAR</h1>
  </div>
  <!-- <div>{{ object.track.name }}
      [{{ object.price }} ETH]
       ({{ object.track.length }} days,
      {{ object.racers_needed }} racers needed,
      {{ object.track.refills }} refills)
      {{ object.racers_count }} joined</div> -->
  <form method="post" id='join-form_js' class="content-flex">
    <div >
      {% bootstrap_form form %}
      <div class="title-fuel-block">
        <img src='/static/img/fuel-icon.png'>
        <span>CHOOSE FUEL</span>
      </div>
      <div class="user-fuel-block">
        <div class='ava' style="background-image: url('{{ request.user.customer.avatar.url }}')"></div>
        <div class="text">Fill a tank with cryptocurrency you believe in and go to the track. И можно сюда добавить еще немножечко текста потому что одна строчка для описания выглядит совсем уныло. . .</div>
      </div>
      {% csrf_token %}
        {% for currency in currencies %}
          <div class="overlay-slider-rage {{ currency.code|lower }}-overlay cointype {{ currency.code|lower }}-cointype" >
            <div class="coin-code">{{ currency.code }}</div>
            <div class="flex-position">
              <input id='{{ currency.code }}' type="text" class="example {{ currency.code|lower }}-slide" value="" />
              <div class="input-coin-hands">
                <input  data-coin-name='{{ currency.code }}' class="{{ currency.code }} input-val-range-slider_js" value="0" type='text'/>
                <span>%</span>
              </div>
            </div>
          </div>
        {% endfor %}
  <!--
      <div class="overlay-slider-rage xrp-overlay cointype xrp-cointype" >
        <div class="coin-code">xrp</div>
        <input id='XRP' type="text" class="example xrp-slide"  value="" />
        <input data-coin-name='XRP' class="XRP input-val-range-slider_js" value="0" type='number'/>%
      </div>

      <div class="overlay-slider-rage dash-overlay cointype dash-cointype" >
        <div>DASH</div>
        <input id='DASH' type="text" class="example" value="" />
        <input data-coin-name='DASH' class="DASH input-val-range-slider_js" value="0" type='number' />%
      </div> -->


      <div id='alert-fuel-form_js' class="isHidden alert alert-warning" role="alert">
        Please choose exactly 100%
      </div>
      <!-- {% for currency in currencies %}{{ currency.code }}{% endfor %} -->

      <!-- Example: <br><code>{ {% for currency in currencies %}"{{ currency.code }}": "0.05"{% if not forloop.last %}, {% endif %}{% endfor %} }</code> -->

    </div>
    <div class="img-barel">
      <img src='/static/img/fuel.png'>
    </div>
      <div class="overlay-for-btn">
        <a href='/game/'>
          <img src='/static/img/BACK.png'>
        </a>
        <button  class="btn btn-primary" id='btn-submit-fuel-form_js' disabled >START</button>
      </div>
  </form>
</div>
{% endblock %}

game/templates/game/leave_race.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <h2>Race #{{ object.pk }}</h2>
  <div>{{ object.track.name }}
      [{{ object.price }} ETH]
       ({{ object.track.length }} days,
      {{ object.racers_needed }} racers needed,
      {{ object.track.refills }} refills)
      {{ object.racers_count }} joined</div>
  <h3>Are you sure you want to leave this race?</h3>
  <form method="post">
    {% csrf_token %}
    {% buttons %}
        <button type="submit" class="btn btn-danger">Leave</button>
        <a href="{% url 'game:watch' pk=object.pk %}" class="btn btn-default">Cancel</a>
    {% endbuttons %}
  </form>
{% endblock %}

game/templates/game/race_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block head %}
  <title>Search race</title>
  <link rel="stylesheet" href="/static/css/list-race.css">
{% endblock %}

{% block script %}
  <script src='/static/js/race-list.js'></script>
{% endblock %}

{% block content %}
<div class="container">

    <div class="track overlay">
      <section class="section4 row">
        {% if not_started.count %}
          <div class="col-sm-6">
            <div class="content d-flex align-items-center flex-column">
              <div class="container d-flex justify-content-center">
                <h1 class="title-yellow white-title">AWAITING PLAYERS</h1>
              </div>
              {% for race in not_started %}
                {% include 'game/includes/race_list_item.html' %}
              {% endfor %}
            </div>
          </div>
        {% endif %}
        {% if ongoing.count %}
          <div class="col-sm-6">
            <div class="content d-flex align-items-center flex-column">
              <div class="container d-flex justify-content-center">
                <h1 class="title-yellow">ACTIVE RACE</h1>
              </div>
              {% for race in ongoing %}
                {% include 'game/includes/race_list_item.html' %}
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </section>
    </div>
{#    {% bootstrap_pagination page_obj %}#}
</div>
{% endblock %}

game/templates/game/select_skin.html
{% extends 'base.html' %}
{% load staticfiles bootstrap4 %}

{% block head %}
  <title>Select car</title>
  <link rel="stylesheet" href="{% static 'css/for-form.css' %}">
  <link rel="stylesheet" href="{% static 'css/slide.css' %}">
  <link rel="stylesheet" href="{% static 'slick-1.8.0/slick/slick.css' %}">
{% endblock %}

{% block script %}
  <script src='/static/slick-1.8.0/slick/slick.min.js'></script>
  <script src='/static/js/slider.js'></script>
{% endblock %}

{% block content %}

<div class="hidden-xs-up user-skin-id_js">{{request.user.customer.car_skin.id}}</div>
<form method="post" class="container">

    {% csrf_token %}
    {% with form.fields.car_skin_val as car_skin_field %}
    <div class="container d-flex justify-content-center">
      <h1 class="title-yellow">CHOOSE A CAR</h1>
    </div>
          <div id='slider'>
            {% for car_skin in car_skin_field.queryset %}
              <label class="slide" data-skin-pk='{{ car_skin.pk }}'>
                  <div class="hidden-xs-up cost">{{ car_skin.price|floatformat:3 }}</div>
                  <img src="/uploads/{{ car_skin.side_view }}" alt="{{ car_skin.name }}">
                  <input data-skin-pk='{{ car_skin.pk }}' {% if car_skin.price %}disabled{% endif %} type="radio" name="car_skin_val" id="{{ car_skin.pk }}" value="{{ car_skin.pk }}" {% if car_skin == request.user.customer.car_skin %}checked{% endif %}>
                  <!-- {{ car_skin.name }} -->
              </label>
            {% endfor %}
          </div>
    {% endwith %}
    <div class="d-flex buttons">
      <a href='/game/' id='back-btn'>
        <img src='/static/img/BACK.png'>
      </a>
        <div id='prev-a' style="background-image: url('/static/img/prev.png')"></div>
        {% for car_skin in form.fields.car_skin_val.queryset %}
          {% if forloop.counter == 1 %}
            {% if car_skin.price %}
              <button type="submit" class="btn blue-btn_js" name="action" disabled value="car_skin">BUY - {{ car_skin.price|floatformat:3 }} <img src='/static/img/eth.ico' width='30px'></button>
            {% else %}
              <button type="submit" class="btn blue-btn_js" name="action" value="car_skin">FREE</button>
            {% endif %}
          {% endif %}
        {% endfor %}
        <div id='next-a' style="background-image: url('/static/img/next.png')"></div>
    </div>
</form>
{% endblock %}